version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: api/v1/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  liquibase:
    image: liquibase/liquibase:latest
    volumes:
      - .:/liquibase/workspace
    working_dir: /liquibase/workspace
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    command: --defaultsFile=liquibase/changelog/liquibase.properties update    
volumes:
  pgdata: